/// Quantized frame from color-quantizer crate
#[derive(Debug, Clone)]
pub struct QuantizedFrame {
    /// Width in pixels
    pub width: u32,
    /// Height in pixels
    pub height: u32,
    /// Palette (up to 256 RGBA colors)
    pub palette: Vec<[u8; 4]>,
    /// Indexed color data (one byte per pixel)
    pub indices: Vec<u8>,
    /// Index of transparent color
    pub transparent_index: u8,
    /// Presentation timestamp in milliseconds
    pub pts_ms: u64,
    /// Duration in milliseconds
    pub duration_ms: u64,
}

/// A single BDN XML subtitle event
#[derive(Debug, Clone)]
pub struct BdnEvent {
    /// Event index (for filename generation)
    pub index: u32,
    /// In timecode "HH:MM:SS:FF" (24fps)
    pub in_tc: String,
    /// Out timecode "HH:MM:SS:FF" (24fps)
    pub out_tc: String,
    /// PNG filename (e.g. "0001.png")
    pub graphic: String,
    /// X position
    pub x: u32,
    /// Y position
    pub y: u32,
    /// Width of graphic
    pub width: u32,
    /// Height of graphic
    pub height: u32,
    /// Whether this is a forced subtitle
    pub forced: bool,
}

/// Complete BDN XML document
#[derive(Debug, Clone)]
pub struct BdnXml {
    /// BDN version (e.g. "0.93")
    pub version: String,
    /// Description text
    pub description: String,
    /// Name/title
    pub name: String,
    /// Frame rate (e.g. "24")
    pub frame_rate: String,
    /// Display width
    pub display_width: u32,
    /// Display height
    pub display_height: u32,
    /// Format (e.g. "PAL", "NTSC")
    pub format: String,
    /// All events
    pub events: Vec<BdnEvent>,
}

impl BdnXml {
    pub fn new(name: impl Into<String>, width: u32, height: u32) -> Self {
        Self {
            version: "0.93".to_string(),
            description: "Generated by ass2sup".to_string(),
            name: name.into(),
            frame_rate: "24".to_string(),
            display_width: width,
            display_height: height,
            format: if height <= 576 { "PAL" } else { "NTSC" }.to_string(),
            events: Vec::new(),
        }
    }

    pub fn add_event(&mut self, event: BdnEvent) {
        self.events.push(event);
    }
}
