#[derive(Debug, Clone, PartialEq)]
pub enum OverrideTag {
    Pos { x: f64, y: f64 },
    Move { x1: f64, y1: f64, x2: f64, y2: f64, t1: u64, t2: u64 },
    Fade { duration_in: u64, duration_out: u64 },
    FadeComplex { duration_in: u64, duration_out: u64, alpha_start: u8, alpha_mid: u8, alpha_end: u8 },
    Transform { tag: String, duration: u64, accel: f64 },
    FontName(String),
    FontSize(f64),
    Bold(bool),
    BoldWeight(u32),
    Italic(bool),
    Underline(bool),
    Strikeout(bool),
    PrimaryColor(super::color::AssColor),
    SecondaryColor(super::color::AssColor),
    OutlineColor(super::color::AssColor),
    ShadowColor(super::color::AssColor),
    Alpha { value: u8 },
    PrimaryAlpha { value: u8 },
    SecondaryAlpha { value: u8 },
    OutlineAlpha { value: u8 },
    ShadowAlpha { value: u8 },
    Rotation { x: f64, y: f64, z: f64 },
    Scale { x: f64, y: f64 },
    Spacing(f64),
    Blur(f64),
    GaussianBlur(f64),
    Border(f64),
    BorderX(f64),
    BorderY(f64),
    Shadow(f64),
    ShadowX(f64),
    ShadowY(f64),
    Clip { x1: f64, y1: f64, x2: f64, y2: f64 },
    ClipInverse { x1: f64, y1: f64, x2: f64, y2: f64 },
    ClipDrawing { scale: f32, commands: String },
    ClipInverseDrawing { scale: f32, commands: String },
    Alignment(u8),
    AlignmentNumpad(u8),
    WrapStyle(u8),
    WritingMode(u8),
    Charset(u8),
    Karaoke {
        style: super::karaoke::KaraokeStyle,
        duration: u64,
    },
    Reset(String),
    ResetAll,
    DrawingMode(u8),
    BaselineOffset(f64),
    Unknown(String),
}
